# Generated by Django 5.2 on 2025-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='organizatio_name_2d216c_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['email'], name='organizatio_email_8060eb_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='organizatio_created_b3d583_idx'),
        ),
    ]
