# Generated by Django 5.2 on 2025-05-21 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(choices=[('microsoft_365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('dropbox', 'DropBox'), ('slack', 'Slack'), ('zoom', 'Zoom'), ('jira', 'Jira')], max_length=100)),
                ('connection_id', models.CharField(max_length=100, unique=True)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_endpoint', models.CharField(max_length=255)),
                ('auth_type', models.CharField(max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('not_connected', 'Not Connected')], default='not_connected', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source_configs', to='organization.organization')),
            ],
            options={
                'db_table': 'data_source_config',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_name'], name='data_source_service_4b0478_idx'), models.Index(fields=['connection_id'], name='data_source_connect_eccafa_idx'), models.Index(fields=['status'], name='data_source_status_8a1e52_idx')],
            },
        ),
    ]
