# Generated by Django 5.2 on 2025-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_datasourceconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceconfig',
            name='status',
            field=models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('invalid_credentials', 'Invalid Credentials'), ('insufficient_permissions', 'Insufficient Permissions'), ('connection_error', 'Connection Error')], default='not_connected', max_length=50),
        ),
    ]
