# Generated by Django 5.2 on 2025-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_datasourceconfig_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceconfig',
            name='extraction_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=50),
        ),
        migrations.AddField(
            model_name='datasourceconfig',
            name='last_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
