# Generated by Django 5.2 on 2025-05-27 23:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_datasourceconfig_extraction_status_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasourceconfig',
            name='data_source_connect_eccafa_idx',
        ),
        migrations.RemoveField(
            model_name='datasourceconfig',
            name='connection_id',
        ),
        migrations.AlterField(
            model_name='datasourceconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
